# Generated by Django 5.2.8 on 2025-12-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "quantity"], name="products_is_acti_d7265b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_featured", "is_active"],
                name="products_categor_6e2600_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"], name="products_is_acti_b753ec_idx"
            ),
        ),
    ]
